const backExercises = [
    {
      name: 'Pull-ups',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Hang from a pull-up bar with your palms facing away from you. Pull your body upward until your chin is above the bar, then lower yourself back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Deadlifts',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Stand with your feet hip-width apart and grip a barbell with your hands shoulder-width apart. Keeping your back straight, push through your heels and lift the barbell off the ground, then lower it back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Bent-Over Rows',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Hold a barbell or dumbbells with an overhand grip and bend forward at the hips. Keep your back straight and pull the weight toward your chest, squeezing your shoulder blades together. Lower the weight back down and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Lat Pulldowns',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Sit at a lat pulldown machine and grip the bar with your hands wider than shoulder-width apart. Pull the bar down to your chest, squeezing your shoulder blades together, then slowly release it back up to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Seated Cable Rows',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Sit at a cable row machine with your feet against the footrests and hold the handles with an overhand grip. Sit up straight and pull the handles toward your body, squeezing your shoulder blades together. Extend your arms back out and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Single-Arm Dumbbell Rows',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Place one knee and one hand on a bench, holding a dumbbell in your opposite hand. Pull the dumbbell up toward your hip, squeezing your shoulder blade, then lower it back down and repeat. Switch sides and repeat with the other arm.',
      image: require('../exercises/images/s.png'), 
    },
    {
      name: 'T-Bar Rows',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Straddle a T-bar row machine and grip the handles with both hands. Keep your back straight and pull the handles toward your chest, squeezing your shoulder blades together. Lower the handles back down and repeat.',
      image: require('../exercises/images/s.png'), 
    },
    {
      name: 'Wide-Grip Pull-ups',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Hang from a pull-up bar with your palms facing away from you and your hands wider than shoulder-width apart. Pull your body upward until your chin is above the bar, then lower yourself back down to the starting position.',
      image: require('../exercises/images/s.png'), 
    },
    {
      name: 'Inverted Rows',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Lie underneath a bar or Smith machine with your body straight and your heels on the ground. Reach up and grab the bar with an overhand grip, then pull your chest up to the bar, squeezing your shoulder blades together. Lower yourself back down and repeat.',
      image: require('../exercises/images/s.png'), 
    },
    {
      name: 'Single-Arm Cable Rows',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Stand facing a cable machine with the handle attached at waist height. Take a step back and hold the handle with one hand. Pull the handle toward your body, squeezing your shoulder blade, then release it back and repeat with the other arm.',
      image: require('../exercises/images/s.png'),     
    },
    {
      name: 'Machine Pullovers',
      muscleGroup: 'Back',
      category: 'Isolation',
      description: 'Sit in a pullover machine and place your forearms on the pads. Push the pads forward, extending your arms in front of you, then slowly release them back to the starting position and repeat.',
      image: require('../exercises/images/s.png'),     
    },
    {
      name: 'Lat Pulldowns',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Sit at a lat pulldown machine and grip the bar with your hands close together, palms facing you. Pull the bar down to your chest, squeezing your shoulder blades together, then slowly release it back up to the starting position.',
      image: require('../exercises/images/s.png'),     
    },
    {
      name: 'Wide-Grip Cable Rows',
      muscleGroup: 'Back',
      category: 'Compound',
      description: 'Sit at a cable row machine and grip the handles with your hands wider than shoulder-width apart. Pull the handles toward your body, squeezing your shoulder blades together, then slowly release them back to the starting position.',
      image: require('../exercises/images/s.png'),        
    },
    {
      name: 'Dumbbell Pullovers',
      muscleGroup: 'Back',
      category: 'Isolation',
      description: 'Lie on a bench with a dumbbell held above your chest, arms extended. Lower the dumbbell back behind your head, keeping a slight bend in your elbows, then raise it back up to the starting position.',
      image: require('../exercises/images/s.png'),        
    }]

  export default backExercises;