const chestExercises = [
    {
      name: 'Barbell Bench Press',
      muscleGroup: 'Chest',
      category: 'Compound',
      description: 'Lie on a bench and lift a barbell from your chest to arms fully extended. Lower the barbell back to your chest and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Dumbbell Bench Press',
      muscleGroup: 'Chest',
      category: 'Compound',
      description: 'Lie on a bench and hold dumbbells at shoulder level. Press the dumbbells upward until your arms are fully extended. Lower the dumbbells back to shoulder level and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Push-ups',
      muscleGroup: 'Chest',
      category: 'Compound',
      description: 'Start in a plank position with your hands placed slightly wider than shoulder-width apart. Lower your body until your chest nearly touches the ground, then push yourself back up to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Incline Bench Press',
      muscleGroup: 'Chest',
      category: 'Compound',
      description: 'Lie on an incline bench and lift a barbell from your chest to arms fully extended. Lower the barbell back to your chest and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Dumbbell Flyes',
      muscleGroup: 'Chest',
      category: 'Isolation',
      description: 'Lie on a bench with dumbbells in each hand, palms facing each other. Extend your arms out to the sides, keeping a slight bend in your elbows. Bring the dumbbells back up to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Chest Press Machine',
      muscleGroup: 'Chest',
      category: 'Machine',
      description: 'Sit on a chest press machine and grip the handles. Push the handles forward until your arms are fully extended, then slowly bring them back to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Decline Bench Press',
      muscleGroup: 'Chest',
      category: 'Compound',
      description: 'Lie on a decline bench and lift a barbell from your chest to arms fully extended. Lower the barbell back to your chest and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Cable Crossover',
      muscleGroup: 'Chest',
      category: 'Isolation',
      description: 'Stand between two cable machines and hold the handles with your palms facing upward. Step forward and lean slightly forward. Bring your hands together in front of your chest, crossing them over each other. Slowly release back to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Machine Chest Flyes',
      muscleGroup: 'Chest',
      category: 'Machine',
      description: 'Sit on a chest fly machine and grip the handles. Bring your arms forward until they meet in front of your chest, then slowly return them to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Weighted Push-ups',
      muscleGroup: 'Chest',
      category: 'Compound',
      description: 'Place a weighted plate on your upper back. Start in a push-up position and lower your body until your chest nearly touches the floor, then push yourself back up to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Chest Dips',
      muscleGroup: 'Chest',
      category: 'Compound',
      description: 'Hang from parallel bars with your arms fully extended. Lower your body until your upper arms are parallel to the ground, then push yourself back up to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Machine Chest Press',
      muscleGroup: 'Chest',
      category: 'Machine',
      description: 'Sit on a chest press machine and grip the handles. Push the handles forward until your arms are fully extended, then slowly bring them back to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Dumbbell Incline Press',
      muscleGroup: 'Chest',
      category: 'Compound',
      description: 'Lie on an incline bench and hold dumbbells at shoulder level. Press the dumbbells upward until your arms are fully extended. Lower the dumbbells back to shoulder level and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Low Cable Crossover',
      muscleGroup: 'Chest',
      category: 'Isolation',
      description: 'Set the pulleys on a cable machine to the lowest position. Stand facing away from the machine and hold the handles with your palms facing downward. Step forward and lean slightly forward. Bring your hands together in front of your chest, crossing them over each other. Slowly release back to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Pec Deck Flyes',
      muscleGroup: 'Chest',
      category: 'Machine',
      description: 'Sit on a pec deck machine and position your forearms against the pads. Bring your forearms together in front of your chest, squeezing your pecs, then slowly return to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Machine Incline Press',
      muscleGroup: 'Chest',
      category: 'Machine',
      description: 'Sit on an incline press machine and grip the handles. Push the handles forward until your arms are fully extended, then slowly bring them back to the starting position and repeat.',
      image: require('../exercises/images/s.png'),
    }]

export default chestExercises;