const deltExercises = [
    {
      name: 'Barbell Shoulder Press',
      muscleGroup: 'Shoulders',
      category: 'Compound',
      description: 'Stand with your feet shoulder-width apart and hold a barbell at shoulder level. Press the barbell upward until your arms are fully extended, then lower it back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Dumbbell Shoulder Press',
      muscleGroup: 'Shoulders',
      category: 'Compound',
      description: 'Sit on a bench with a dumbbell in each hand at shoulder level. Press the dumbbells upward until your arms are fully extended, then lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Front Raises',
      muscleGroup: 'Shoulders',
      category: 'Isolation',
      description: 'Stand with your feet shoulder-width apart and hold a dumbbell in each hand, palms facing your body. Raise the dumbbells forward and upward until they are at shoulder level, then lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Lateral Raises',
      muscleGroup: 'Shoulders',
      category: 'Isolation',
      description: 'Stand with your feet shoulder-width apart and hold a dumbbell in each hand, palms facing your body. Raise the dumbbells out to the sides until they are at shoulder level, then lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Bent-Over Reverse Flyes',
      muscleGroup: 'Shoulders',
      category: 'Isolation',
      description: 'Bend forward at the hips with a dumbbell in each hand, palms facing each other. Raise the dumbbells out to the sides until your arms are parallel to the ground, then lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Upright Rows',
      muscleGroup: 'Shoulders',
      category: 'Compound',
      description: 'Stand with your feet shoulder-width apart and hold a barbell with an overhand grip, hands placed close together. Pull the barbell upward, keeping it close to your body, until it reaches chest level. Lower it back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Seated Dumbbell Shoulder Press',
      muscleGroup: 'Shoulders',
      category: 'Compound',
      description: 'Sit on a bench with a dumbbell in each hand at shoulder level. Press the dumbbells upward until your arms are fully extended, then lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Seated Overhead Press Machine',
      muscleGroup: 'Shoulders',
      category: 'Machine',
      description: 'Sit at an overhead press machine and grip the handles. Push the handles upward until your arms are fully extended, then slowly lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Seated Arnold Press',
      muscleGroup: 'Shoulders',
      category: 'Compound',
      description: 'Sit on a bench with a dumbbell in each hand at shoulder level, palms facing your body. Rotate the dumbbells as you press them upward, so your palms face outward at the top of the movement. Reverse the rotation as you lower the dumbbells back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Dumbbell Shrugs',
      muscleGroup: 'Shoulders',
      category: 'Isolation',
      description: 'Stand with your feet shoulder-width apart and hold a dumbbell in each hand, palms facing your body. Shrug your shoulders upward as high as possible, then lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Seated Dumbbell Lateral Raises',
      muscleGroup: 'Shoulders',
      category: 'Isolation',
      description: 'Sit on a bench with a dumbbell in each hand, palms facing your body. Raise the dumbbells out to the sides until they are at shoulder level, then lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Face Pulls',
      muscleGroup: 'Shoulders',
      category: 'Compound',
      description: 'Attach a rope to a cable machine at chest height. Stand with your feet shoulder-width apart and hold the rope with an overhand grip. Pull the rope toward your face, squeezing your shoulder blades together, then slowly release it back to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Rear Delt Flyes',
      muscleGroup: 'Shoulders',
      category: 'Isolation',
      description: 'Bend forward at the hips with a dumbbell in each hand, palms facing each other. Raise the dumbbells out to the sides, keeping a slight bend in your elbows, until your arms are parallel to the ground. Lower them back down to the starting position.',
      image: require('../exercises/images/s.png'),
    },
    {
      name: 'Push Press',
      muscleGroup: 'Shoulders',
      category: 'Compound',
      description: 'Stand with your feet shoulder-width apart and hold a barbell at shoulder level in front of you. Bend your knees and use your legs to help press the barbell overhead. Lower it back down to the starting position.',
      image: require('../exercises/images/s.png'),
    }]

    export default deltExercises;